{
  "name":"scb02ea",
  "briefing": "GDI has kept a stranglehold on Egypt for many years.  Set up a forward \nattack base in your area.  To do this you must double click on your Mobile \nConstruction Vehicle. (MCV) From here you can begin to build a base. \nThis area contains plenty of Tiberium, so establishing the base should be \neasy.",
  "team":"nod",
  "height":26,
  "width":36,
  "y":5,
  "x":9,
  "player":"BadGuy",
  "theater":"desert",
  "cash":{
    "GoodGuy":2000,
    "BadGuy":4000
  },
  "videos" : {
    "briefing":"nod/nod2"
  },
  "requirements":{
          "infantry":["minigunner","engineer"],
          "buildings":["construction-yard","barracks","refinery","tiberium-silo","hand-of-nod","power-plant"],
          "turrets":[],
          "vehicles":["buggy","jeep","harvester","mcv"],
          "trees":["desert-tree-08","desert-tree-18"],
          "tiberium":["tiberium"]
      },
      "buildable":{
          "infantry":["engineer","minigunner"],
          "buildings":["refinery","tiberium-silo","barracks","hand-of-nod","power-plant"]
      },
      "terrain":{
          "rocks": [
            [0,0],[1,0],[2,0],[3,0],[4,0],[5,0],[6,0],[7,0],[8,0],[9,0],[10,0],[11,0],[12,0],[14,0],[15,0],[16,0],[17,0],[18,0],[19,0],[20,0],
            [12,1],[13,1],[14,1],

            [30,0],[31,0],
            [30,1],[31,1],
                    [31,2],[32,2],
                    [31,3],[32,3],
                    [31,4],[32,4],
                    [31,5],


            [31,8],[31,9],[31,10],
                   [32,9], [32,10],[32,11],[32,12],[32,13],
                    [33,11],[33,12],[33,13],
                    [34,12],[34,13],
                        [35,13],[35,14],

            [30,16],[31,16],[32,16],
            [33,17],[34,17],[35,17],

            [20,19],[21,19],
            [20,20],[21,20],
            [20,21],[21,21],
            [20,22],[21,22],
                    [21,23],[22,23],
            [20,24],[21,24],
            [21,25],[22,25],

            [23,11],[24,11],

            [12,21],[13,21],[14,21],
            [12,22],[13,22],[14,22],[15,22],
            [12,23],[13,23],[14,23],

            [0,18],[1,18],[2,18],
            [3,19],[4,19],[5,19],[6,19],

            [11,4],[12,4],
            [11,5],
            [10,6],[11,6],
            [10,7],[11,7],
            [10,8],[11,8],
            [10,9],[11,9],
            [10,10],[11,10],
            [9,11],[10,11],
            [5,12],[6,12],[7,12],[8,12],[9,12],
            [2,13],[3,13],[4,13],[5,13],[6,13],[7,13],
            [3,14]


          ]


      },


      "starting":{
        "triggers":[
            {"name":"condition","condition":"(game.count(\"vehicles\",\"GoodGuy\")==0 && game.count(\"infantry\",\"GoodGuy\") == 0 && game.count(\"buildings\",\"GoodGuy\") == 0)",
           "action":"success"},
           {"name":"condition","condition":"(game.count(\"vehicles\",\"BadGuy\")==0 && game.count(\"infantry\",\"BadGuy\") == 0 && game.count(\"buildings\",\"BadGuy\") == 0)",
            "action":"failure"}],
        "trees":[
          {
            "name":"desert-tree-08",
            "y":15,
            "x":31
          },
          {
            "name":"desert-tree-18",
            "y":13,
            "x":31
          },
          {
            "name":"desert-tree-08",
            "y":8,
            "x":22
          },
          {
            "name":"desert-tree-08",
            "y":8,
            "x":23
          },
          {
            "name":"desert-tree-08",
            "y":17,
            "x":18
          },
          {
            "name":"desert-tree-08",
            "y":1,
            "x":0
          },
          {
            "name":"desert-tree-08",
            "y":19,
            "x":0
          },
          {
            "name":"desert-tree-08",
            "y":19,
            "x":1
          },
          {
            "name":"desert-tree-08",
            "y":20,
            "x":13
          },
          {
            "name":"desert-tree-08",
            "y":4,
            "x":10
          },
          {
            "name":"desert-tree-08",
            "y":17,
            "x":3
          }
        ],
        "tiberium":[
          {
            "y":25,
            "x":8,
            "name":"tiberium",
            "stage":10
          },
          {
            "y":25,
            "x":7,
            "name":"tiberium",
            "stage":6
          },
          {
            "y":25,
            "x":5,
            "name":"tiberium",
            "stage":2
          },
          {
            "y":25,
            "x":4,
            "name":"tiberium",
            "stage":10
          },
          {
            "y":25,
            "x":2,
            "name":"tiberium",
            "stage":12
          },
          {
            "y":25,
            "x":1,
            "name":"tiberium",
            "stage":1
          },
          {
            "y":24,
            "x":9,
            "name":"tiberium",
            "stage":9
          },
          {
            "y":24,
            "x":7,
            "name":"tiberium",
            "stage":6
          },
          {
            "y":24,
            "x":6,
            "name":"tiberium",
            "stage":10
          },
          {
            "y":24,
            "x":5,
            "name":"tiberium",
            "stage":11
          },
          {
            "y":24,
            "x":4,
            "name":"tiberium",
            "stage":4
          },
          {
            "y":24,
            "x":3,
            "name":"tiberium",
            "stage":9
          },
          {
            "y":24,
            "x":2,
            "name":"tiberium",
            "stage":10
          },
          {
            "y":24,
            "x":1,
            "name":"tiberium",
            "stage":8
          },
          {
            "y":23,
            "x":9,
            "name":"tiberium",
            "stage":1
          },
          {
            "y":23,
            "x":8,
            "name":"tiberium",
            "stage":10
          },
          {
            "y":23,
            "x":7,
            "name":"tiberium",
            "stage":4
          },
          {
            "y":23,
            "x":6,
            "name":"tiberium",
            "stage":1
          },
          {
            "y":23,
            "x":5,
            "name":"tiberium",
            "stage":7
          },
          {
            "y":23,
            "x":4,
            "name":"tiberium",
            "stage":6
          },
          {
            "y":23,
            "x":2,
            "name":"tiberium",
            "stage":11
          },
          {
            "y":23,
            "x":1,
            "name":"tiberium",
            "stage":12
          },
          {
            "y":22,
            "x":8,
            "name":"tiberium",
            "stage":2
          },
          {
            "y":22,
            "x":7,
            "name":"tiberium",
            "stage":10
          },
          {
            "y":22,
            "x":6,
            "name":"tiberium",
            "stage":11
          },
          {
            "y":22,
            "x":5,
            "name":"tiberium",
            "stage":10
          },
          {
            "y":22,
            "x":3,
            "name":"tiberium",
            "stage":6
          },
          {
            "y":22,
            "x":2,
            "name":"tiberium",
            "stage":12
          },
          {
            "y":22,
            "x":1,
            "name":"tiberium",
            "stage":7
          },
          {
            "y":21,
            "x":6,
            "name":"tiberium",
            "stage":10
          },
          {
            "y":21,
            "x":5,
            "name":"tiberium",
            "stage":12
          },
          {
            "y":21,
            "x":4,
            "name":"tiberium",
            "stage":9
          },
          {
            "y":21,
            "x":3,
            "name":"tiberium",
            "stage":8
          },
          {
            "y":21,
            "x":2,
            "name":"tiberium",
            "stage":5
          },
          {
            "y":20,
            "x":5,
            "name":"tiberium",
            "stage":12
          },
          {
            "y":20,
            "x":4,
            "name":"tiberium",
            "stage":12
          },
          {
            "y":20,
            "x":3,
            "name":"tiberium",
            "stage":10
          },
          {
            "y":20,
            "x":2,
            "name":"tiberium",
            "stage":12
          },
          {
            "y":16,
            "x":23,
            "name":"tiberium",
            "stage":4
          },
          {
            "y":15,
            "x":24,
            "name":"tiberium",
            "stage":2
          },
          {
            "y":14,
            "x":25,
            "name":"tiberium",
            "stage":8
          },
          {
            "y":14,
            "x":24,
            "name":"tiberium",
            "stage":12
          },
          {
            "y":14,
            "x":23,
            "name":"tiberium",
            "stage":8
          },
          {
            "y":14,
            "x":22,
            "name":"tiberium",
            "stage":10
          },
          {
            "y":14,
            "x":21,
            "name":"tiberium",
            "stage":10
          },
          {
            "y":14,
            "x":20,
            "name":"tiberium",
            "stage":9
          },
          {
            "y":14,
            "x":15,
            "name":"tiberium",
            "stage":2
          },
          {
            "y":14,
            "x":13,
            "name":"tiberium",
            "stage":4
          },
          {
            "y":14,
            "x":12,
            "name":"tiberium",
            "stage":12
          },
          {
            "y":13,
            "x":26,
            "name":"tiberium",
            "stage":7
          },
          {
            "y":13,
            "x":25,
            "name":"tiberium",
            "stage":12
          },
          {
            "y":13,
            "x":23,
            "name":"tiberium",
            "stage":6
          },
          {
            "y":13,
            "x":22,
            "name":"tiberium",
            "stage":7
          },
          {
            "y":13,
            "x":21,
            "name":"tiberium",
            "stage":1
          },
          {
            "y":13,
            "x":15,
            "name":"tiberium",
            "stage":6
          },
          {
            "y":13,
            "x":14,
            "name":"tiberium",
            "stage":3
          },
          {
            "y":13,
            "x":13,
            "name":"tiberium",
            "stage":6
          },
          {
            "y":12,
            "x":27,
            "name":"tiberium",
            "stage":6
          },
          {
            "y":12,
            "x":26,
            "name":"tiberium",
            "stage":10
          },
          {
            "y":12,
            "x":25,
            "name":"tiberium",
            "stage":1
          },
          {
            "y":12,
            "x":24,
            "name":"tiberium",
            "stage":6
          },
          {
            "y":12,
            "x":23,
            "name":"tiberium",
            "stage":11
          },
          {
            "y":12,
            "x":22,
            "name":"tiberium",
            "stage":2
          },
          {
            "y":12,
            "x":15,
            "name":"tiberium",
            "stage":11
          },
          {
            "y":12,
            "x":14,
            "name":"tiberium",
            "stage":4
          },
          {
            "y":12,
            "x":13,
            "name":"tiberium",
            "stage":9
          },
          {
            "y":11,
            "x":27,
            "name":"tiberium",
            "stage":11
          },
          {
            "y":11,
            "x":26,
            "name":"tiberium",
            "stage":2
          },
          {
            "y":11,
            "x":25,
            "name":"tiberium",
            "stage":6
          },
          {
            "y":11,
            "x":16,
            "name":"tiberium",
            "stage":11
          },
          {
            "y":11,
            "x":15,
            "name":"tiberium",
            "stage":5
          },
          {
            "y":11,
            "x":13,
            "name":"tiberium",
            "stage":2
          },
          {
            "y":11,
            "x":12,
            "name":"tiberium",
            "stage":11
          },
          {
            "y":10,
            "x":17,
            "name":"tiberium",
            "stage":1
          },
          {
            "y":10,
            "x":16,
            "name":"tiberium",
            "stage":9
          },
          {
            "y":10,
            "x":14,
            "name":"tiberium",
            "stage":9
          },
          {
            "y":10,
            "x":13,
            "name":"tiberium",
            "stage":1
          },
          {
            "y":9,
            "x":16,
            "name":"tiberium",
            "stage":4
          },
          {
            "y":9,
            "x":15,
            "name":"tiberium",
            "stage":12
          },
          {
            "y":9,
            "x":14,
            "name":"tiberium",
            "stage":9
          },
          {
            "y":9,
            "x":13,
            "name":"tiberium",
            "stage":5
          },
          {
            "y":9,
            "x":12,
            "name":"tiberium",
            "stage":3
          },
          {
            "y":8,
            "x":15,
            "name":"tiberium",
            "stage":10
          },
          {
            "y":8,
            "x":14,
            "name":"tiberium",
            "stage":9
          },
          {
            "y":8,
            "x":13,
            "name":"tiberium",
            "stage":12
          },
          {
            "y":8,
            "x":12,
            "name":"tiberium",
            "stage":1
          },
          {
            "y":7,
            "x":14,
            "name":"tiberium",
            "stage":1
          }
        ],
        "infantry":[
          {
            "player":"GoodGuy",
            "team":"gdi",
            "name":"minigunner",
            "y":2.25,
            "x":7.75,
            "orders":{
              "type":"area guard"
            },
            "direction":3
          },
          {
            "player":"GoodGuy",
            "team":"gdi",
            "name":"minigunner",
            "y":1.75,
            "x":7.75,
            "orders":{
              "type":"area guard"
            },
            "direction":3
          },
          {
            "player":"GoodGuy",
            "team":"gdi",
            "name":"minigunner",
            "y":2.25,
            "x":6.25,
            "orders":{
              "type":"area guard"
            },
            "direction":3
          },
          {
            "player":"GoodGuy",
            "team":"gdi",
            "name":"minigunner",
            "y":12.25,
            "x":2.75,
            "orders":{
              "type":"area guard"
            },
            "direction":0
          },
          {
            "player":"GoodGuy",
            "team":"gdi",
            "name":"minigunner",
            "y":12.75,
            "x":2.25,
            "orders":{
              "type":"area guard"
            },
            "direction":0
          },
          {
            "player":"GoodGuy",
            "team":"gdi",
            "name":"minigunner",
            "y":4.75,
            "x":7.25,
            "orders":{
              "type":"area guard"
            },
            "direction":0
          },
          {
            "player":"GoodGuy",
            "team":"gdi",
            "name":"minigunner",
            "y":4.75,
            "x":8.75,
            "orders":{
              "type":"area guard"
            },
            "direction":0
          },
          {
            "player":"GoodGuy",
            "team":"gdi",
            "name":"minigunner",
            "y":1.75,
            "x":7.25,
            "orders":{
              "type":"area guard"
            },
            "direction":3
          },
          {
            "player":"GoodGuy",
            "team":"gdi",
            "name":"minigunner",
            "y":17.75,
            "x":5.75,
            "orders":{
              "type":"hunt"
            },
            "direction":0
          },
          {
            "player":"GoodGuy",
            "team":"gdi",
            "name":"minigunner",
            "y":17.75,
            "x":4.25,
            "orders":{
              "type":"hunt"
            },
            "direction":0
          },
          {
            "player":"GoodGuy",
            "team":"gdi",
            "name":"minigunner",
            "y":2.25,
            "x":34.75,
            "orders":{
              "type":"hunt"
            },
            "direction":0
          },
          {
            "player":"GoodGuy",
            "team":"gdi",
            "name":"minigunner",
            "y":1.75,
            "x":33.25,
            "orders":{
              "type":"hunt"
            },
            "direction":0
          },
          {
            "player":"GoodGuy",
            "team":"gdi",
            "name":"minigunner",
            "y":8.75,
            "x":24.75,
            "orders":{
              "type":"area guard"
            },
            "direction":0
          },
          {
            "player":"BadGuy",
            "team":"nod",
            "name":"minigunner",
            "y":23.75,
            "x":33.25,
            "orders":{
              "type":"guard"
            },
            "direction":0
          },
          {
            "player":"BadGuy",
            "team":"nod",
            "name":"minigunner",
            "y":24.25,
            "x":33.75,
            "orders":{
              "type":"guard"
            },
            "direction":0
          },
          {
            "player":"BadGuy",
            "team":"nod",
            "name":"minigunner",
            "y":23.75,
            "x":33.75,
            "orders":{
              "type":"guard"
            },
            "direction":0
          },
          {
            "player":"BadGuy",
            "team":"nod",
            "name":"minigunner",
            "y":23.75,
            "x":28.75,
            "orders":{
              "type":"guard"
            },
            "direction":0
          },
          {
            "player":"BadGuy",
            "team":"nod",
            "name":"minigunner",
            "y":23.75,
            "x":27.25,
            "orders":{
              "type":"guard"
            },
            "direction":0
          },
          {
            "player":"BadGuy",
            "team":"nod",
            "name":"minigunner",
            "y":24.25,
            "x":33.25,
            "orders":{
              "type":"guard"
            },
            "direction":0
          },
          {
            "player":"BadGuy",
            "team":"nod",
            "name":"minigunner",
            "y":24.25,
            "x":27.25,
            "orders":{
              "type":"guard"
            },
            "direction":0
          },
          {
            "player":"BadGuy",
            "team":"nod",
            "name":"minigunner",
            "y":24.25,
            "x":28.75,
            "orders":{
              "type":"guard"
            },
            "direction":0
          }
        ],
        "buildings":[
          {
            "player":"GoodGuy",
            "team":"gdi",
            "name":"refinery",
            "y":4,
            "x":4
          },
          {
            "player":"GoodGuy",
            "team":"gdi",
            "name":"construction-yard",
            "y":5,
            "x":7
          },
          {
            "player":"GoodGuy",
            "team":"gdi",
            "name":"power-plant",
            "y":8,
            "x":8
          },
          {
            "player":"GoodGuy",
            "team":"gdi",
            "name":"tiberium-silo",
            "y":8,
            "x":6
          },
          {
            "player":"GoodGuy",
            "team":"gdi",
            "name":"tiberium-silo",
            "y":10,
            "x":6
          },
          {
            "player":"GoodGuy",
            "team":"gdi",
            "name":"barracks",
            "y":9,
            "x":4
          }
        ],
        "buildings":[
          {
            "player":"GoodGuy",
            "team":"gdi",
            "name":"refinery",
            "y":4,
            "x":4
          },
          {
            "player":"GoodGuy",
            "team":"gdi",
            "name":"construction-yard",
            "y":5,
            "x":7
          },
          {
            "player":"GoodGuy",
            "team":"gdi",
            "name":"power-plant",
            "y":8,
            "x":8
          },
          {
            "player":"GoodGuy",
            "team":"gdi",
            "name":"tiberium-silo",
            "y":8,
            "x":6
          },
          {
            "player":"GoodGuy",
            "team":"gdi",
            "name":"tiberium-silo",
            "y":10,
            "x":6
          },
          {
            "player":"GoodGuy",
            "team":"gdi",
            "name":"barracks",
            "y":9,
            "x":4
          }
        ],
        "vehicles":[
          {
            "player":"GoodGuy",
            "team":"gdi",
            "name":"jeep",
            "y":1,
            "x":2,
            "direction":12
          },
          {
            "player":"GoodGuy",
            "team":"gdi",
            "name":"jeep",
            "y":9,
            "x":3,
            "direction":20
          },
          {
            "player":"GoodGuy",
            "team":"gdi",
            "name":"jeep",
            "y":4,
            "x":9,
            "direction":4
          },
          {
            "player":"BadGuy",
            "team":"nod",
            "name":"mcv",
            "y":23,
            "x":30,
            "direction":0
          },
          {
            "player":"BadGuy",
            "team":"nod",
            "name":"buggy",
            "y":21,
            "x":29,
            "direction":0
          },
          {
            "player":"BadGuy",
            "team":"nod",
            "name":"buggy",
            "y":21,
            "x":30,
            "direction":0
          },
          {
            "player":"BadGuy",
            "team":"nod",
            "name":"buggy",
            "y":21,
            "x":31,
            "direction":0
          },
          {
            "player":"GoodGuy",
            "team":"gdi",
            "name":"harvester",
            "orders":{"type":"harvest"},
            "y":22,
            "x":8,
            "direction":28,
            "percentLife":0.39453125
          }
        ]
      }
}